get http://localhost:3000/todos/?category=LEARNING&status=PROGRESS

###
get http://localhost:3000/todos/4/

###
post http://localhost:3000/todos/
Content-Type:application/json 

{
 "id": 5,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-11-22"
}

###
get http://localhost:3000/agenda/?date=2021-14-12

###
put http://localhost:3000/todos/6/
Content-Type:application/json 

{
"dueDate": "2021-10-11"
}


###
DELETE http://localhost:3000/todos/4/